### 1. Upload file
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=Boundary123

--Boundary123
Content-Disposition: form-data; name="file"; filename="eshak (1).jpg"
Content-Type: image/png

< D:\Downloads\eshak (1).jpg
--Boundary123--

### 2. Open file by ID
GET http://localhost:8080/api/v1/attach/open/{id}

### 3. Download file by ID
GET http://localhost:8080/api/v1/attach/download/{id}

### 4. Pagination (ADMIN required)
GET http://localhost:8080/api/v1/attach/pagination?page=0&size=10

### 5. Delete file (ADMIN required)
DELETE http://localhost:8080/api/v1/attach/delete/{id}
