### 1. Create Playlist (USER)
POST http://localhost:8080/api/v1/playlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc2NDk0NDcwNiwiZXhwIjoxNzY1Mzc2NzA2fQ.StFVEX0AyZDNSOIMNkKPh553FFODrZ9sSWhTXetE7ctSOpjRqr7nJdwADMd8hNyUy1bMYjopZbyUiDOgTahPMA

{
  "name": "My Playlist",
  "description": "Playlist description",
  "channelId": "4465a761-27a6-4f7f-96e8-022611623e47",
  "status": "PUBLIC",
  "orderNum": 1
}


### 2. Update Playlist (USER and OWNER)
PUT http://localhost:8080/api/v1/playlist/{playlistId}
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "title": "Updated Playlist",
  "description": "Updated playlist description"
}


### 3. Change Playlist Status (USER and OWNER)
PUT http://localhost:8080/api/v1/playlist/{playlistId}/status?status=PUBLIC
Authorization: Bearer <TOKEN>



### 4. Delete Playlist (USER, OWNER, ADMIN)
DELETE http://localhost:8080/api/v1/playlist/{playlistId}
Authorization: Bearer <TOKEN>



### 5. Playlist Pagination (ADMIN)
GET http://localhost:8080/api/v1/playlist/pagination?page=1&size=10
Authorization: Bearer <TOKEN>



### 6. Playlist List By UserId (ADMIN)
GET http://localhost:8080/api/v1/playlist/by-user/{userId}
Authorization: Bearer <TOKEN>



### 7. Get Current User Playlists (USER)
GET http://localhost:8080/api/v1/playlist/my-playlists
Authorization: Bearer <TOKEN>



### 8. Get Channel Playlists (PUBLIC Only)
GET http://localhost:8080/api/v1/playlist/channel/{channelId}



### 9. Get Playlist By Id
GET http://localhost:8080/api/v1/playlist/6dc6bf72-312b-41ba-91fb-0ff63b4f58dc
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc2NDk0NDcwNiwiZXhwIjoxNzY1Mzc2NzA2fQ.StFVEX0AyZDNSOIMNkKPh553FFODrZ9sSWhTXetE7ctSOpjRqr7nJdwADMd8hNyUy1bMYjopZbyUiDOgTahPMA

